# Copy this generated service and add it to the main Docker-compose.yml file

service-<%= serviceName%>:
  build:
    context: ./packages/service-<%= serviceName%>/
    dockerfile: ./Dockerfile-development
  command: sh -c "yarn --no-lockfile && yarn start:dev"
  <% if (dependencies) { %>
  ports:
    - ${PORT:-<%= servicePort%>}:3000
  depends_on:
  <% dependencies.forEach(function(d) { %>
    - <%= d%> <% }); %>
  <% } %>
  env_file: ./packages/service-<%= serviceName%>/.env
  volumes:
    - ./packages/service-<%= serviceName%>:/app
    - <%= serviceName%>-node-modules:/app/node_modules

volumes:
  <%= serviceName%>-node-modules:
